use crate::DorkTemplate;

pub const TEMPLATES: &[DorkTemplate] = &[
    DorkTemplate {
        name: "Dork Template #1",
        category: "Backups",
        site: "internal.lan",
        inurl: "phpmyadmin",
        intitle: "login page",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #2",
        category: "IoT Devices",
        site: "test.org",
        inurl: "ftp",
        intitle: "control panel",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #3",
        category: "Streaming",
        site: "demo.net",
        inurl: "config",
        intitle: "access",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #4",
        category: "Source Code",
        site: "lab.local",
        inurl: "backup",
        intitle: "config",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #5",
        category: "Cameras",
        site: "open.network",
        inurl: "data",
        intitle: "dashboard",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #6",
        category: "Private Keys",
        site: "example.com",
        inurl: "shell",
        intitle: "index of",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #7",
        category: "FTP Servers",
        site: "internal.lan",
        inurl: "scada",
        intitle: "login page",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #8",
        category: "Index Listings",
        site: "test.org",
        inurl: "login",
        intitle: "control panel",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #9",
        category: "Admin Panels",
        site: "demo.net",
        inurl: "dump",
        intitle: "access",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #10",
        category: "DevOps",
        site: "lab.local",
        inurl: "admin",
        intitle: "config",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #11",
        category: "Backups",
        site: "open.network",
        inurl: "phpmyadmin",
        intitle: "dashboard",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #12",
        category: "IoT Devices",
        site: "example.com",
        inurl: "ftp",
        intitle: "index of",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #13",
        category: "Streaming",
        site: "internal.lan",
        inurl: "config",
        intitle: "login page",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #14",
        category: "Source Code",
        site: "test.org",
        inurl: "backup",
        intitle: "control panel",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #15",
        category: "Cameras",
        site: "demo.net",
        inurl: "data",
        intitle: "access",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #16",
        category: "Private Keys",
        site: "lab.local",
        inurl: "shell",
        intitle: "config",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #17",
        category: "FTP Servers",
        site: "open.network",
        inurl: "scada",
        intitle: "dashboard",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #18",
        category: "Index Listings",
        site: "example.com",
        inurl: "login",
        intitle: "index of",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #19",
        category: "Admin Panels",
        site: "internal.lan",
        inurl: "dump",
        intitle: "login page",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #20",
        category: "DevOps",
        site: "test.org",
        inurl: "admin",
        intitle: "control panel",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #21",
        category: "Backups",
        site: "demo.net",
        inurl: "phpmyadmin",
        intitle: "access",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #22",
        category: "IoT Devices",
        site: "lab.local",
        inurl: "ftp",
        intitle: "config",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #23",
        category: "Streaming",
        site: "open.network",
        inurl: "config",
        intitle: "dashboard",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #24",
        category: "Source Code",
        site: "example.com",
        inurl: "backup",
        intitle: "index of",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #25",
        category: "Cameras",
        site: "internal.lan",
        inurl: "data",
        intitle: "login page",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #26",
        category: "Private Keys",
        site: "test.org",
        inurl: "shell",
        intitle: "control panel",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #27",
        category: "FTP Servers",
        site: "demo.net",
        inurl: "scada",
        intitle: "access",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #28",
        category: "Index Listings",
        site: "lab.local",
        inurl: "login",
        intitle: "config",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #29",
        category: "Admin Panels",
        site: "open.network",
        inurl: "dump",
        intitle: "dashboard",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #30",
        category: "DevOps",
        site: "example.com",
        inurl: "admin",
        intitle: "index of",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #31",
        category: "Backups",
        site: "internal.lan",
        inurl: "phpmyadmin",
        intitle: "login page",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #32",
        category: "IoT Devices",
        site: "test.org",
        inurl: "ftp",
        intitle: "control panel",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #33",
        category: "Streaming",
        site: "demo.net",
        inurl: "config",
        intitle: "access",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #34",
        category: "Source Code",
        site: "lab.local",
        inurl: "backup",
        intitle: "config",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #35",
        category: "Cameras",
        site: "open.network",
        inurl: "data",
        intitle: "dashboard",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #36",
        category: "Private Keys",
        site: "example.com",
        inurl: "shell",
        intitle: "index of",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #37",
        category: "FTP Servers",
        site: "internal.lan",
        inurl: "scada",
        intitle: "login page",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #38",
        category: "Index Listings",
        site: "test.org",
        inurl: "login",
        intitle: "control panel",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #39",
        category: "Admin Panels",
        site: "demo.net",
        inurl: "dump",
        intitle: "access",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #40",
        category: "DevOps",
        site: "lab.local",
        inurl: "admin",
        intitle: "config",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #41",
        category: "Backups",
        site: "open.network",
        inurl: "phpmyadmin",
        intitle: "dashboard",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #42",
        category: "IoT Devices",
        site: "example.com",
        inurl: "ftp",
        intitle: "index of",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #43",
        category: "Streaming",
        site: "internal.lan",
        inurl: "config",
        intitle: "login page",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #44",
        category: "Source Code",
        site: "test.org",
        inurl: "backup",
        intitle: "control panel",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #45",
        category: "Cameras",
        site: "demo.net",
        inurl: "data",
        intitle: "access",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #46",
        category: "Private Keys",
        site: "lab.local",
        inurl: "shell",
        intitle: "config",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #47",
        category: "FTP Servers",
        site: "open.network",
        inurl: "scada",
        intitle: "dashboard",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #48",
        category: "Index Listings",
        site: "example.com",
        inurl: "login",
        intitle: "index of",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #49",
        category: "Admin Panels",
        site: "internal.lan",
        inurl: "dump",
        intitle: "login page",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #50",
        category: "DevOps",
        site: "test.org",
        inurl: "admin",
        intitle: "control panel",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #51",
        category: "Backups",
        site: "demo.net",
        inurl: "phpmyadmin",
        intitle: "access",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #52",
        category: "IoT Devices",
        site: "lab.local",
        inurl: "ftp",
        intitle: "config",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #53",
        category: "Streaming",
        site: "open.network",
        inurl: "config",
        intitle: "dashboard",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #54",
        category: "Source Code",
        site: "example.com",
        inurl: "backup",
        intitle: "index of",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #55",
        category: "Cameras",
        site: "internal.lan",
        inurl: "data",
        intitle: "login page",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #56",
        category: "Private Keys",
        site: "test.org",
        inurl: "shell",
        intitle: "control panel",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #57",
        category: "FTP Servers",
        site: "demo.net",
        inurl: "scada",
        intitle: "access",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #58",
        category: "Index Listings",
        site: "lab.local",
        inurl: "login",
        intitle: "config",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #59",
        category: "Admin Panels",
        site: "open.network",
        inurl: "dump",
        intitle: "dashboard",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #60",
        category: "DevOps",
        site: "example.com",
        inurl: "admin",
        intitle: "index of",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #61",
        category: "Backups",
        site: "internal.lan",
        inurl: "phpmyadmin",
        intitle: "login page",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #62",
        category: "IoT Devices",
        site: "test.org",
        inurl: "ftp",
        intitle: "control panel",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #63",
        category: "Streaming",
        site: "demo.net",
        inurl: "config",
        intitle: "access",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #64",
        category: "Source Code",
        site: "lab.local",
        inurl: "backup",
        intitle: "config",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #65",
        category: "Cameras",
        site: "open.network",
        inurl: "data",
        intitle: "dashboard",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #66",
        category: "Private Keys",
        site: "example.com",
        inurl: "shell",
        intitle: "index of",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #67",
        category: "FTP Servers",
        site: "internal.lan",
        inurl: "scada",
        intitle: "login page",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #68",
        category: "Index Listings",
        site: "test.org",
        inurl: "login",
        intitle: "control panel",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #69",
        category: "Admin Panels",
        site: "demo.net",
        inurl: "dump",
        intitle: "access",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #70",
        category: "DevOps",
        site: "lab.local",
        inurl: "admin",
        intitle: "config",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #71",
        category: "Backups",
        site: "open.network",
        inurl: "phpmyadmin",
        intitle: "dashboard",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #72",
        category: "IoT Devices",
        site: "example.com",
        inurl: "ftp",
        intitle: "index of",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #73",
        category: "Streaming",
        site: "internal.lan",
        inurl: "config",
        intitle: "login page",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #74",
        category: "Source Code",
        site: "test.org",
        inurl: "backup",
        intitle: "control panel",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #75",
        category: "Cameras",
        site: "demo.net",
        inurl: "data",
        intitle: "access",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #76",
        category: "Private Keys",
        site: "lab.local",
        inurl: "shell",
        intitle: "config",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #77",
        category: "FTP Servers",
        site: "open.network",
        inurl: "scada",
        intitle: "dashboard",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #78",
        category: "Index Listings",
        site: "example.com",
        inurl: "login",
        intitle: "index of",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #79",
        category: "Admin Panels",
        site: "internal.lan",
        inurl: "dump",
        intitle: "login page",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #80",
        category: "DevOps",
        site: "test.org",
        inurl: "admin",
        intitle: "control panel",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #81",
        category: "Backups",
        site: "demo.net",
        inurl: "phpmyadmin",
        intitle: "access",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #82",
        category: "IoT Devices",
        site: "lab.local",
        inurl: "ftp",
        intitle: "config",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #83",
        category: "Streaming",
        site: "open.network",
        inurl: "config",
        intitle: "dashboard",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #84",
        category: "Source Code",
        site: "example.com",
        inurl: "backup",
        intitle: "index of",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #85",
        category: "Cameras",
        site: "internal.lan",
        inurl: "data",
        intitle: "login page",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #86",
        category: "Private Keys",
        site: "test.org",
        inurl: "shell",
        intitle: "control panel",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #87",
        category: "FTP Servers",
        site: "demo.net",
        inurl: "scada",
        intitle: "access",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #88",
        category: "Index Listings",
        site: "lab.local",
        inurl: "login",
        intitle: "config",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #89",
        category: "Admin Panels",
        site: "open.network",
        inurl: "dump",
        intitle: "dashboard",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #90",
        category: "DevOps",
        site: "example.com",
        inurl: "admin",
        intitle: "index of",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #91",
        category: "Backups",
        site: "internal.lan",
        inurl: "phpmyadmin",
        intitle: "login page",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #92",
        category: "IoT Devices",
        site: "test.org",
        inurl: "ftp",
        intitle: "control panel",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #93",
        category: "Streaming",
        site: "demo.net",
        inurl: "config",
        intitle: "access",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #94",
        category: "Source Code",
        site: "lab.local",
        inurl: "backup",
        intitle: "config",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #95",
        category: "Cameras",
        site: "open.network",
        inurl: "data",
        intitle: "dashboard",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #96",
        category: "Private Keys",
        site: "example.com",
        inurl: "shell",
        intitle: "index of",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #97",
        category: "FTP Servers",
        site: "internal.lan",
        inurl: "scada",
        intitle: "login page",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #98",
        category: "Index Listings",
        site: "test.org",
        inurl: "login",
        intitle: "control panel",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #99",
        category: "Admin Panels",
        site: "demo.net",
        inurl: "dump",
        intitle: "access",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #100",
        category: "DevOps",
        site: "lab.local",
        inurl: "admin",
        intitle: "config",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #101",
        category: "Backups",
        site: "open.network",
        inurl: "phpmyadmin",
        intitle: "dashboard",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #102",
        category: "IoT Devices",
        site: "example.com",
        inurl: "ftp",
        intitle: "index of",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #103",
        category: "Streaming",
        site: "internal.lan",
        inurl: "config",
        intitle: "login page",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #104",
        category: "Source Code",
        site: "test.org",
        inurl: "backup",
        intitle: "control panel",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #105",
        category: "Cameras",
        site: "demo.net",
        inurl: "data",
        intitle: "access",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #106",
        category: "Private Keys",
        site: "lab.local",
        inurl: "shell",
        intitle: "config",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #107",
        category: "FTP Servers",
        site: "open.network",
        inurl: "scada",
        intitle: "dashboard",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #108",
        category: "Index Listings",
        site: "example.com",
        inurl: "login",
        intitle: "index of",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #109",
        category: "Admin Panels",
        site: "internal.lan",
        inurl: "dump",
        intitle: "login page",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #110",
        category: "DevOps",
        site: "test.org",
        inurl: "admin",
        intitle: "control panel",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #111",
        category: "Backups",
        site: "demo.net",
        inurl: "phpmyadmin",
        intitle: "access",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #112",
        category: "IoT Devices",
        site: "lab.local",
        inurl: "ftp",
        intitle: "config",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #113",
        category: "Streaming",
        site: "open.network",
        inurl: "config",
        intitle: "dashboard",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #114",
        category: "Source Code",
        site: "example.com",
        inurl: "backup",
        intitle: "index of",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #115",
        category: "Cameras",
        site: "internal.lan",
        inurl: "data",
        intitle: "login page",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #116",
        category: "Private Keys",
        site: "test.org",
        inurl: "shell",
        intitle: "control panel",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #117",
        category: "FTP Servers",
        site: "demo.net",
        inurl: "scada",
        intitle: "access",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #118",
        category: "Index Listings",
        site: "lab.local",
        inurl: "login",
        intitle: "config",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #119",
        category: "Admin Panels",
        site: "open.network",
        inurl: "dump",
        intitle: "dashboard",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #120",
        category: "DevOps",
        site: "example.com",
        inurl: "admin",
        intitle: "index of",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #121",
        category: "Backups",
        site: "internal.lan",
        inurl: "phpmyadmin",
        intitle: "login page",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #122",
        category: "IoT Devices",
        site: "test.org",
        inurl: "ftp",
        intitle: "control panel",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #123",
        category: "Streaming",
        site: "demo.net",
        inurl: "config",
        intitle: "access",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #124",
        category: "Source Code",
        site: "lab.local",
        inurl: "backup",
        intitle: "config",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #125",
        category: "Cameras",
        site: "open.network",
        inurl: "data",
        intitle: "dashboard",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #126",
        category: "Private Keys",
        site: "example.com",
        inurl: "shell",
        intitle: "index of",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #127",
        category: "FTP Servers",
        site: "internal.lan",
        inurl: "scada",
        intitle: "login page",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #128",
        category: "Index Listings",
        site: "test.org",
        inurl: "login",
        intitle: "control panel",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #129",
        category: "Admin Panels",
        site: "demo.net",
        inurl: "dump",
        intitle: "access",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #130",
        category: "DevOps",
        site: "lab.local",
        inurl: "admin",
        intitle: "config",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #131",
        category: "Backups",
        site: "open.network",
        inurl: "phpmyadmin",
        intitle: "dashboard",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #132",
        category: "IoT Devices",
        site: "example.com",
        inurl: "ftp",
        intitle: "index of",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #133",
        category: "Streaming",
        site: "internal.lan",
        inurl: "config",
        intitle: "login page",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #134",
        category: "Source Code",
        site: "test.org",
        inurl: "backup",
        intitle: "control panel",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #135",
        category: "Cameras",
        site: "demo.net",
        inurl: "data",
        intitle: "access",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #136",
        category: "Private Keys",
        site: "lab.local",
        inurl: "shell",
        intitle: "config",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #137",
        category: "FTP Servers",
        site: "open.network",
        inurl: "scada",
        intitle: "dashboard",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #138",
        category: "Index Listings",
        site: "example.com",
        inurl: "login",
        intitle: "index of",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #139",
        category: "Admin Panels",
        site: "internal.lan",
        inurl: "dump",
        intitle: "login page",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #140",
        category: "DevOps",
        site: "test.org",
        inurl: "admin",
        intitle: "control panel",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #141",
        category: "Backups",
        site: "demo.net",
        inurl: "phpmyadmin",
        intitle: "access",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #142",
        category: "IoT Devices",
        site: "lab.local",
        inurl: "ftp",
        intitle: "config",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #143",
        category: "Streaming",
        site: "open.network",
        inurl: "config",
        intitle: "dashboard",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #144",
        category: "Source Code",
        site: "example.com",
        inurl: "backup",
        intitle: "index of",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #145",
        category: "Cameras",
        site: "internal.lan",
        inurl: "data",
        intitle: "login page",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #146",
        category: "Private Keys",
        site: "test.org",
        inurl: "shell",
        intitle: "control panel",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #147",
        category: "FTP Servers",
        site: "demo.net",
        inurl: "scada",
        intitle: "access",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #148",
        category: "Index Listings",
        site: "lab.local",
        inurl: "login",
        intitle: "config",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #149",
        category: "Admin Panels",
        site: "open.network",
        inurl: "dump",
        intitle: "dashboard",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #150",
        category: "DevOps",
        site: "example.com",
        inurl: "admin",
        intitle: "index of",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #151",
        category: "Backups",
        site: "internal.lan",
        inurl: "phpmyadmin",
        intitle: "login page",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #152",
        category: "IoT Devices",
        site: "test.org",
        inurl: "ftp",
        intitle: "control panel",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #153",
        category: "Streaming",
        site: "demo.net",
        inurl: "config",
        intitle: "access",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #154",
        category: "Source Code",
        site: "lab.local",
        inurl: "backup",
        intitle: "config",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #155",
        category: "Cameras",
        site: "open.network",
        inurl: "data",
        intitle: "dashboard",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #156",
        category: "Private Keys",
        site: "example.com",
        inurl: "shell",
        intitle: "index of",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #157",
        category: "FTP Servers",
        site: "internal.lan",
        inurl: "scada",
        intitle: "login page",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #158",
        category: "Index Listings",
        site: "test.org",
        inurl: "login",
        intitle: "control panel",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #159",
        category: "Admin Panels",
        site: "demo.net",
        inurl: "dump",
        intitle: "access",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #160",
        category: "DevOps",
        site: "lab.local",
        inurl: "admin",
        intitle: "config",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #161",
        category: "Backups",
        site: "open.network",
        inurl: "phpmyadmin",
        intitle: "dashboard",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #162",
        category: "IoT Devices",
        site: "example.com",
        inurl: "ftp",
        intitle: "index of",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #163",
        category: "Streaming",
        site: "internal.lan",
        inurl: "config",
        intitle: "login page",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #164",
        category: "Source Code",
        site: "test.org",
        inurl: "backup",
        intitle: "control panel",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #165",
        category: "Cameras",
        site: "demo.net",
        inurl: "data",
        intitle: "access",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #166",
        category: "Private Keys",
        site: "lab.local",
        inurl: "shell",
        intitle: "config",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #167",
        category: "FTP Servers",
        site: "open.network",
        inurl: "scada",
        intitle: "dashboard",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #168",
        category: "Index Listings",
        site: "example.com",
        inurl: "login",
        intitle: "index of",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #169",
        category: "Admin Panels",
        site: "internal.lan",
        inurl: "dump",
        intitle: "login page",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #170",
        category: "DevOps",
        site: "test.org",
        inurl: "admin",
        intitle: "control panel",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #171",
        category: "Backups",
        site: "demo.net",
        inurl: "phpmyadmin",
        intitle: "access",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #172",
        category: "IoT Devices",
        site: "lab.local",
        inurl: "ftp",
        intitle: "config",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #173",
        category: "Streaming",
        site: "open.network",
        inurl: "config",
        intitle: "dashboard",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #174",
        category: "Source Code",
        site: "example.com",
        inurl: "backup",
        intitle: "index of",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #175",
        category: "Cameras",
        site: "internal.lan",
        inurl: "data",
        intitle: "login page",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #176",
        category: "Private Keys",
        site: "test.org",
        inurl: "shell",
        intitle: "control panel",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #177",
        category: "FTP Servers",
        site: "demo.net",
        inurl: "scada",
        intitle: "access",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #178",
        category: "Index Listings",
        site: "lab.local",
        inurl: "login",
        intitle: "config",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #179",
        category: "Admin Panels",
        site: "open.network",
        inurl: "dump",
        intitle: "dashboard",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #180",
        category: "DevOps",
        site: "example.com",
        inurl: "admin",
        intitle: "index of",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #181",
        category: "Backups",
        site: "internal.lan",
        inurl: "phpmyadmin",
        intitle: "login page",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #182",
        category: "IoT Devices",
        site: "test.org",
        inurl: "ftp",
        intitle: "control panel",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #183",
        category: "Streaming",
        site: "demo.net",
        inurl: "config",
        intitle: "access",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #184",
        category: "Source Code",
        site: "lab.local",
        inurl: "backup",
        intitle: "config",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #185",
        category: "Cameras",
        site: "open.network",
        inurl: "data",
        intitle: "dashboard",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #186",
        category: "Private Keys",
        site: "example.com",
        inurl: "shell",
        intitle: "index of",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #187",
        category: "FTP Servers",
        site: "internal.lan",
        inurl: "scada",
        intitle: "login page",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #188",
        category: "Index Listings",
        site: "test.org",
        inurl: "login",
        intitle: "control panel",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #189",
        category: "Admin Panels",
        site: "demo.net",
        inurl: "dump",
        intitle: "access",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #190",
        category: "DevOps",
        site: "lab.local",
        inurl: "admin",
        intitle: "config",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #191",
        category: "Backups",
        site: "open.network",
        inurl: "phpmyadmin",
        intitle: "dashboard",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #192",
        category: "IoT Devices",
        site: "example.com",
        inurl: "ftp",
        intitle: "index of",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Dork Template #193",
        category: "Streaming",
        site: "internal.lan",
        inurl: "config",
        intitle: "login page",
        filetype: "txt",
        intext: "admin",
    },
    DorkTemplate {
        name: "Dork Template #194",
        category: "Source Code",
        site: "test.org",
        inurl: "backup",
        intitle: "control panel",
        filetype: "conf",
        intext: "api_key",
    },
    DorkTemplate {
        name: "Dork Template #195",
        category: "Cameras",
        site: "demo.net",
        inurl: "data",
        intitle: "access",
        filetype: "json",
        intext: "root",
    },
    DorkTemplate {
        name: "Dork Template #196",
        category: "Private Keys",
        site: "lab.local",
        inurl: "shell",
        intitle: "config",
        filetype: "log",
        intext: "confidential",
    },
    DorkTemplate {
        name: "Dork Template #197",
        category: "FTP Servers",
        site: "open.network",
        inurl: "scada",
        intitle: "dashboard",
        filetype: "xml",
        intext: "DB_USER",
    },
    DorkTemplate {
        name: "Dork Template #198",
        category: "Index Listings",
        site: "example.com",
        inurl: "login",
        intitle: "index of",
        filetype: "ini",
        intext: "SECRET_KEY",
    },
    DorkTemplate {
        name: "Dork Template #199",
        category: "Admin Panels",
        site: "internal.lan",
        inurl: "dump",
        intitle: "login page",
        filetype: "bak",
        intext: "token",
    },
    DorkTemplate {
        name: "Dork Template #200",
        category: "DevOps",
        site: "test.org",
        inurl: "admin",
        intitle: "control panel",
        filetype: "sql",
        intext: "password",
    },
    DorkTemplate {
        name: "Sensitive Online Shopping Info - site:mail.* intitle:Dashboard",
        category: "Sensitive Online Shopping Info",
        site: "mail.*",
        inurl: "",
        intitle: "Dashboard",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Sensitive Online Shopping Info - inurl:product-list.php?id=",
        category: "Sensitive Online Shopping Info",
        site: "",
        inurl: "product-list.php?id=",
        intitle: "",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Sensitive Online Shopping Info - inurl:/commodities.php?id=",
        category: "Sensitive Online Shopping Info",
        site: "",
        inurl: "/commodities.php?id=",
        intitle: "",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Sensitive Online Shopping Info - intext:\"Dumping data for table `orders`\"",
        category: "Sensitive Online Shopping Info",
        site: "",
        inurl: "",
        intitle: "",
        filetype: "",
        intext: "Dumping data for table `orders`",
    },
    DorkTemplate {
        name: "Sensitive Online Shopping Info - dcid= bn= pin code=",
        category: "Sensitive Online Shopping Info",
        site: "",
        inurl: "",
        intitle: "",
        filetype: "",
        intext: "dcid= bn= pin code=",
    },
    DorkTemplate {
        name: "Sensitive Online Shopping Info - intext:\"powered by Hosting Controller\" intitle:Hosting.Controller",
        category: "Sensitive Online Shopping Info",
        site: "",
        inurl: "",
        intitle: "Hosting.Controller",
        filetype: "",
        intext: "powered by Hosting Controller",
    },
    DorkTemplate {
        name: "Sensitive Online Shopping Info - site:ups.com intitle:\"Ups Package tracking\" intext:\"1Z ### ### ## #### ### #\"",
        category: "Sensitive Online Shopping Info",
        site: "ups.com",
        inurl: "",
        intitle: "Ups Package tracking",
        filetype: "",
        intext: "1Z ### ### ## #### ### #",
    },
    DorkTemplate {
        name: "Sensitive Online Shopping Info - inurl:midicart.mdb",
        category: "Sensitive Online Shopping Info",
        site: "",
        inurl: "midicart.mdb",
        intitle: "",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Sensitive Online Shopping Info - inurl:shopdbtest.asp",
        category: "Sensitive Online Shopping Info",
        site: "",
        inurl: "shopdbtest.asp",
        intitle: "",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Sensitive Online Shopping Info - \"More Info about MetaCart Free\"",
        category: "Sensitive Online Shopping Info",
        site: "",
        inurl: "",
        intitle: "",
        filetype: "",
        intext: "More Info about MetaCart Free",
    },
    DorkTemplate {
        name: "Sensitive Online Shopping Info - inurl:\"/database/comersus.mdb\"",
        category: "Sensitive Online Shopping Info",
        site: "",
        inurl: "/database/comersus.mdb",
        intitle: "",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Sensitive Online Shopping Info - inurl:\"shopadmin.asp\" \"Shop Administrators only\"",
        category: "Sensitive Online Shopping Info",
        site: "",
        inurl: "shopadmin.asp",
        intitle: "",
        filetype: "",
        intext: "Shop Administrators only",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - site:.edu filetype:xls \"root\" database",
        category: "Files Containing Juicy Info",
        site: ".edu",
        inurl: "",
        intitle: "",
        filetype: "xls",
        intext: "\"root\" database",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - intext:\"proftpd.conf\" \"index of\"",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "",
        intitle: "",
        filetype: "",
        intext: "proftpd.conf \"index of\"",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - \"PHP Fatal error:\" ext:log OR ext:txt",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "",
        intitle: "",
        filetype: "log OR txt",
        intext: "PHP Fatal error:",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - intitle:\"GlobalProtect Portal\"",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "",
        intitle: "GlobalProtect Portal",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - intitle:\"/zircote/swagger-php\"",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "",
        intitle: "/zircote/swagger-php",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - intitle:\"index of\" setting.php",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "",
        intitle: "index of",
        filetype: "",
        intext: "setting.php",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - intext:\"dhcpd.conf\" \"index of\"",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "",
        intitle: "",
        filetype: "",
        intext: "dhcpd.conf \"index of\"",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - site:preprod.* * inurl:login",
        category: "Files Containing Juicy Info",
        site: "preprod.*",
        inurl: "login",
        intitle: "",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - intitle:index of /etc/openldap",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "",
        intitle: "index of /etc/openldap",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - site:uat.* * inurl:login",
        category: "Files Containing Juicy Info",
        site: "uat.*",
        inurl: "login",
        intitle: "",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - inurl:pastebin intitle:mastercard",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "pastebin",
        intitle: "mastercard",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - intitle:Index of \"/etc/network\" | \"/etc/cni/net.d\"",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "",
        intitle: "Index of \"/etc/network\" | \"/etc/cni/net.d\"",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - \"configmap.yaml\" | \"config.yaml\" | \"*-config.yaml\" intitle:\"index of\"",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "",
        intitle: "index of",
        filetype: "",
        intext: "configmap.yaml | config.yaml | *-config.yaml",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - \"rbac.yaml\" | \"role.yaml\" | \"rolebinding.yaml\" | \"*-rbac.yaml\" intitle:\"index of\"",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "",
        intitle: "index of",
        filetype: "",
        intext: "rbac.yaml | role.yaml | rolebinding.yaml | *-rbac.yaml",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - inurl:/s3.amazonaws.com ext:xml intext:index of -site:github.com",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "/s3.amazonaws.com",
        intitle: "",
        filetype: "xml",
        intext: "index of",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - intitle:index of db.py",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "",
        intitle: "index of db.py",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - inurl:/HappyAxis.jsp",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "/HappyAxis.jsp",
        intitle: "",
        filetype: "",
        intext: "",
    },
    DorkTemplate {
        name: "Files Containing Juicy Info - \"PasswordStore\" ext:txt",
        category: "Files Containing Juicy Info",
        site: "",
        inurl: "",
        intitle: "",
        filetype: "txt",
        intext: "PasswordStore",
    },
];
