[package]
name = "google_dork_builder"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
copypasta = "0.10.2"
open = "5.3.2"
urlencoding = "2.1.3"
serde_json = "1.0.140"
serde = {version = "1.0.219", features = ["derive"]}